### PR TITLE
Add function set location

### PR DESCRIPTION
**Pull request by noshuai**
such as fbsimctl xxxxxxxxx set_location 39.9 116.39

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by lawrencelomax** [comment]
Looks good, just one thing. Please write a [Unit Test for your new action](https://github.com/facebook/FBSimulatorControl/blob/master/fbsimctl/FBSimulatorControlKitTests/Tests/Unit/CommandParsersTests.swift#L189). This should be pretty easy to do.

**Comment by lawrencelomax** [comment]
Once you've signed the CLA, I'll be able to merge this. Thanks a lot!

**Comment by lawrencelomax** [comment]
@facebook-github-bot-8 shipit

**Comment by lawrencelomax** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-6** [comment]
Thanks for importing.If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3763975) to review internal test results.

**Pull request closed without merging**
