### PR TITLE
Adding example projects to README.md

### PR DESCRIPTION
**Pull request by davidlawson**

### CODE REVIEW

**Comment by davidlawson** [comment]
I also came across:
* https://github.com/makhov/fbsimulatorcontrol-example-cli-app
* https://github.com/gblotter/FBSimulatorControlDemo
* https://github.com/azalan/SimCtrlCLI/

**Comment by lawrencelomax** [comment]
I think you should add `fbsimctl` into that list as well! otherwise this is good

**Comment by davidlawson** [comment]
All done!

**Comment by lawrencelomax** [comment]
@facebook-github-bot shipit

**Comment by lawrencelomax** [comment]
Great, thanks. I'm shipping this now and and I think a robot will close when it lands.

**Pull request closed without merging**
