### PR TITLE
Use NSRunningApplication for finding Simulator.app processes

### PR DESCRIPTION
**Pull request by plu**

### CODE REVIEW

**Comment by plu** [comment]
I'm not sure what's your policy on using `AppKit` APIs there. I hope this will turn out more reliable than the `SMCopyAllJobDictionaries` version of it :).

**Comment by lawrencelomax** [comment]
This makes a lot of sense. We're using `AppKit` already and the `NSWorkspace` APIs, so there's no reason that we can't use this. 

I'm thinking that writing an e2e test here in the cli tests is also something that we want to do as this could be easy to regress otherwise. We really want to test that launching via `Simulator.app` and then running `fbsimctl` again will yield the appropriate process info for any of the launched Simulator apps. This is currently only covered in `testNoInterferenceBeetweenDeviceSets`

**Comment by plu** [comment]
I'll have a look at the test and come back with another commit shortly.

**Comment by lawrencelomax** [comment]
> I'll have a look at the test and come back with another commit shortly.

I would be happy to land this otherwise, I just don't want to get burned by breakage in process management again!

**Comment by plu** [comment]
This might be enough, right? 

I traced the calls being made, it went through `-[FBSimulatorProcessFetcher simulatorApplicationProcesses]` and should fail if `--booted` does not return the one booted via `Simulator.app`.

**Comment by lawrencelomax** [comment]
`--booted` will contain simulators that are reported to be booted by `CoreSimulator` which is a separate problem to finding the container `Simulator.app` processes that have booted them. The test should correlate that the pid of the container app matches the value that is then shown in the `list` command.

**Comment by plu** [comment]
Ok, thank you for the explanation. I believe now I do understand what to test. For today I'm off, but tomorrow I can probably push another commit providing a proper test case.

**Comment by plu** [comment]
Sorry to bother you again on this topic, I'm still a little confused:

(Current `master` is 8e8a5a18b82bac600e17432d86cc474acc90fb51)

```
plu@plubook ~/Development/FBSimulatorControl[master]$ ./fbsimctl/cli-tests/executable-under-test/bin/fbsimctl 1A1F9F9D-6B8B-434B-A104-6DA54C9B48BF boot
Did Change State => Booting
1A1F9F9D-6B8B-434B-A104-6DA54C9B48BF | iPhone 6 | Booting | iPhone 6 | iOS 9.3: state: Booting
Container Application Did Launch => Process Simulator | PID 1696
1A1F9F9D-6B8B-434B-A104-6DA54C9B48BF | iPhone 6 | Booting | iPhone 6 | iOS 9.3: launch: Process Simulator | PID 1696
Simulator Did launch => Process launchd_sim | PID 1699
1A1F9F9D-6B8B-434B-A104-6DA54C9B48BF | iPhone 6 | Booted | iPhone 6 | iOS 9.3: launch: Process launchd_sim | PID 1699
Did Change State => Booted
1A1F9F9D-6B8B-434B-A104-6DA54C9B48BF | iPhone 6 | Booted | iPhone 6 | iOS 9.3: state: Booted
Connection Did Connect => Bridge: Framebuffer ((null)) | HID (null) | Simulator Bridge: Connected
1A1F9F9D-6B8B-434B-A104-6DA54C9B48BF | iPhone 6 | Booted | iPhone 6 | iOS 9.3: launch: Bridge: Framebuffer ((null)) | HID (null) | Simulator Bridge: Connected
```

Now when I run `list`, I get:

```
plu@plubook ~/Development/FBSimulatorControl[master]$ ./fbsimctl/cli-tests/executable-under-test/bin/fbsimctl --json --pid list
{"event_type":"discrete","subject":{"pid":1699},"timestamp":1472786361,"event_name":"list"}
plu@plubook ~/Development/FBSimulatorControl[master]$ ps auxww | grep 1699
plu               1699   0.0  0.1  2496696   5212   ??  S     7:19AM   0:01.09 launchd_sim /Users/plu/Library/Developer/CoreSimulator/Devices/1A1F9F9D-6B8B-434B-A104-6DA54C9B48BF/data/var/run/launchd_bootstrap.plist
```

The parent process of `1699` is `1` (`launchd`):

```
plu@plubook ~/Development/FBSimulatorControl[master]$ ps -p 1699 -o ppid=
    1
```

But the `Simulator.app` is `1696`:

```
plu@plubook ~/Development/FBSimulatorControl[master]$ ps auxww | grep Simulator.app
plu               1696   0.0  0.8  2624380  63152 s000  S     7:19AM   0:02.20 /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app/Contents/MacOS/Simulator --args -CurrentDeviceUDID 1A1F9F9D-6B8B-434B-A104-6DA54C9B48BF -ConnectHardwareKeyboard 0 -SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPhone-6 1.00 -DeviceSetPath /Users/plu/Library/Developer/CoreSimulator/Devices
```

So the `pid` returned in the `list` command, is not the `Simulator.app`. This is why I'm confused. Does this need to be fixed first, before I'm writing the e2e test for it?

**Comment by lawrencelomax** [comment]
I see the problem now. The `pid` field that is returned is the `pid` of the `launchd_sim` process, but not the `Simulator.app`. This information does exist in the `FBSimulator` implementation, however it isn't exposed in the component that is used for producing the output to the CLI.

We have the `FBiOSTargetFormat` class that is responsible for doing this. We can add a `FBiOSTargetFormatContainerApplicationProcessIdentifier` to this class and extract this from the Simulator where appropriate.

Regardless, I'm happy with the changes in this PR so I'm happy to merge this. We can follow up with a change that will increase our confidence in the correlation of the Simulator Application with a booted Simulator.

**Comment by lawrencelomax** [comment]
@facebook-github-bot shipit

**Comment by lawrencelomax** [comment]
@facebook-github-bot shipit

**Comment by lawrencelomax** [comment]
@facebook-github-bot shipit

**Comment by plu** [comment]
Looks like the bot doesn't want to ship this particular change :).

**Comment by lawrencelomax** [comment]
> Looks like the bot doesn't want to ship this particular change :)

Yep, I've flagged this to the Open Source team. Hopefully this will be fixed soon.

**Comment by lawrencelomax** [comment]
Turns out that there's now a different way of doing this, so your changes should be merged shortly

**Pull request closed without merging**
