### PR TITLE
Removing shared schemes for fbsimctl so Carthage will only find FBSimulatorControl

### PR DESCRIPTION
**Pull request by davidlawson**
A release should also be tagged so Carthage can be used without specifying a branch.

### CODE REVIEW

**Comment by bootstraponline** [comment]
If the schemes are removed then `fbsimctl` can't be built with carthage...

**Comment by lawrencelomax** [comment]
Sorry for the delay... I wasn't aware that carthage would build from the `fbsimctl` scheme. If you just want the `FBSimulatorControl` framework, you should just be able to use the `FBSimulatorControl.xcodeproj`. Is this not sufficient for your needs?

**Comment by davidlawson** [comment]
I must have removed it as it wasn't building.

`carthage update` with `github "facebook/FBSimulatorControl" "master"` doesn't build due to:
```
error: no such module 'Swifter'
```

**Comment by lawrencelomax** [comment]
> carthage update with github "facebook/FBSimulatorControl" "master" doesn't build due to:

I guess I need to add a Cartfile to the repo to fix this then. I would only think that anybody would ever want to build and pull in `FBSimulatorControl` rather than the CLI target itself.

**Comment by lawrencelomax** [comment]
This is way old and apoligies for closing it now. If this is an issue, can you re-open and we can track there.

**Pull request closed without merging**
