### PR TITLE
Use double for duration in FBTestReporterForwarder

### PR DESCRIPTION
**Pull request by robbertvanginkel**
This integerValue should probably be a doubleValue.

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by lawrencelomax** [comment]
Thanks 👍I can merge this when you've signed the CLA.

**Comment by robbertvanginkel** [comment]
Signed the CLA a few days ago, but it seems like it didn't get picked up. Contacted cla@fb.com.

**Comment by lawrencelomax** [comment]
I can't see that the CLA has been signed in the internal tool. Could be a delay here, will follow up.

**Comment by lawrencelomax** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1374571575891535/int_phab) to review.

**Pull request closed without merging**
