### PR TITLE
Xcode 8 @ Travis

### PR DESCRIPTION
**Pull request by plu**

### CODE REVIEW

**Comment by plu** [comment]
Carthage seems to be installed already on the `xcode8` of Travis.

**Comment by plu** [comment]
I hope spawning 13 jobs is still OK with Travis' fair use policy. But I guess this will be temporary anyway.

There's still one test that is red on Xcode 8: `[FBSimulatorTestInjection testInjectsApplicationTestIntoSampleAppOnIOS81Simulator]`. Everything else looks promising.

I have excluded `fbsimctl` related builds on Xcode 8 from the build matrix. It would require Swift syntax changes, that are incompatible between the supported Swift versions of Xcode 7 and 8.

**Comment by plu** [comment]
You can have a look at the bigger build matrix here: https://travis-ci.org/plu/FBSimulatorControl/builds/161532500

**Comment by lawrencelomax** [comment]
This looks good to me, thanks for doing the work here. How I see this working:

1) Land this, which will mean we start running everything against 7.3.1 and the frameworks against 8.
2) I hope to shortly land a diff that will migrate `fbsimctl` to Swift 3/Xcode 8. At the same time I'll update the `.travis.yml` to run the only frameworks against 7.3.1 and everything against xcode 8.

We can decide later what to do about xcode 7 runs, but we could probably just cut down on the matrix a bunch so we only run one of the 7.3.1 variants.

**Comment by plu** [comment]
Sounds good. What do we do about `[FBSimulatorTestInjection testInjectsApplicationTestIntoSampleAppOnIOS81Simulator]`? Drop support for iOS 8 or make it work? What do you think?

**Comment by lawrencelomax** [comment]
> What do we do about `[FBSimulatorTestInjection testInjectsApplicationTestIntoSampleAppOnIOS81Simulator]`?

I think we should currently just skip the test on Xcode 8 or if the runtime isn't available. Then we can decide what to do later. There is [currently a test that does something like this](https://github.com/facebook/FBSimulatorControl/blob/master/FBSimulatorControlTests/Tests/Integration/FBSimulatorFramebufferTests.m).

**Comment by plu** [comment]
It's not about the runtime not being available, 8.1 is available (according to Travis). But setting up the test manager connection is not working, it runs into a timeout.

**Comment by plu** [comment]
Hm. Xcode 8 itself has trouble to execute tests on an 8.x Simulator:

```
* thread #1: tid = 0x6b8693, 0x02ed449a libsystem_kernel.dylib`mach_msg_trap + 10, stop reason = signal SIGSTOP
  * frame #0: 0x02ed449a libsystem_kernel.dylib`mach_msg_trap + 10
    frame #1: 0x02ed3884 libsystem_kernel.dylib`mach_msg + 68
    frame #2: 0x00790eb6 CoreFoundation`__CFRunLoopServiceMachPort + 214
    frame #3: 0x00790298 CoreFoundation`__CFRunLoopRun + 1400
    frame #4: 0x0078fa5b CoreFoundation`CFRunLoopRunSpecific + 443
    frame #5: 0x0078f88b CoreFoundation`CFRunLoopRunInMode + 123
    frame #6: 0x001042d8 Foundation`-[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 309
    frame #7: 0x09d1f5f3 XCTest`-[XCTestDriver _checkForTestManager] + 253
    frame #8: 0x09d1fa18 XCTest`-[XCTestDriver runTestConfiguration:completionHandler:] + 325
    frame #9: 0x09d7351b XCTest`_XCTestMain + 642
    frame #10: 0x0008dfc7 IDEBundleInjection`____XCBundleInjection_block_invoke_2 + 20
    frame #11: 0x0079b050 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 16
    frame #12: 0x00790963 CoreFoundation`__CFRunLoopDoBlocks + 195
    frame #13: 0x007900c8 CoreFoundation`__CFRunLoopRun + 936
    frame #14: 0x0078fa5b CoreFoundation`CFRunLoopRunSpecific + 443
    frame #15: 0x0078f88b CoreFoundation`CFRunLoopRunInMode + 123
    frame #16: 0x03acd2c9 GraphicsServices`GSEventRunModal + 192
    frame #17: 0x03acd106 GraphicsServices`GSEventRun + 104
    frame #18: 0x00c380b6 UIKit`UIApplicationMain + 1526
    frame #19: 0x0001535c Test`main(argc=5, argv=0xbffeb044) + 140 at main.m:14
    frame #20: 0x02bedac9 libdyld.dylib`start + 1

  thread #2: tid = 0x6b86eb, 0x02edc7de libsystem_kernel.dylib`kevent64 + 10
    frame #0: 0x02edc7de libsystem_kernel.dylib`kevent64 + 10
    frame #1: 0x02bb6e1e libdispatch.dylib`_dispatch_mgr_invoke + 245
    frame #2: 0x02bb6b76 libdispatch.dylib`_dispatch_mgr_thread + 60

  thread #4: tid = 0x6b86ed, 0x02edbd5e libsystem_kernel.dylib`__workq_kernreturn + 10
    frame #0: 0x02edbd5e libsystem_kernel.dylib`__workq_kernreturn + 10
    frame #1: 0x02f0834b libsystem_pthread.dylib`_pthread_wqthread + 1289
    frame #2: 0x02f05f56 libsystem_pthread.dylib`start_wqthread + 34

  thread #6: tid = 0x6b86ef, 0x02edbd5e libsystem_kernel.dylib`__workq_kernreturn + 10
    frame #0: 0x02edbd5e libsystem_kernel.dylib`__workq_kernreturn + 10
    frame #1: 0x02f0834b libsystem_pthread.dylib`_pthread_wqthread + 1289
    frame #2: 0x02f05f56 libsystem_pthread.dylib`start_wqthread + 34


*** If you believe this error represents a bug, please attach the log file at /Users/joplunien/Library/Developer/Xcode/DerivedData/Test-edfyasqtutsyvfbdoclfzlatgbkq/Logs/Test/38DD5018-47D8-46AC-88EC-E78B1B5824E9/Session-TestTests-2016-09-21_095508-bHpMEn.log
```

https://gist.githubusercontent.com/plu/85392f1f7e5c6400dde04205a80070cc/raw/7472f5cc202c6517070bbffaad458e31088e2511/gistfile1.txt

**Comment by lawrencelomax** [comment]
I wouldn't expect Xcode 8 to run iOS 8 sims with any reliability. It tends to be that you can only run tests from the n-1 iOS version so we should bypass the test on xcode8 for now.

**Comment by plu** [comment]
Ok. Sounds good! I'll push a change shortly.

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are a Facebook employee, you can view this diff [on Phabricator](https://phabricator.intern.facebook.com/D3899528).

**Comment by lawrencelomax** [comment]
@plu I'm going to land this as part of a stack of changes, so it should be committed later today.

**Comment by plu** [comment]
No hurry :). Thank you!

**Pull request closed without merging**
